MAX_VALUE = 1000000

SUMMARY_SCREEN = 0
POSSESSION_SCREEN = 1
SHOOTING_SCREEN = 2
PASSING_SCREEN = 3
DEFENDING_SCREEN = 4

# index of screenshot for every player attribute
player_data_screenshot_indices = {
    "Rating": SUMMARY_SCREEN,
    "Goals": SUMMARY_SCREEN,
    "Assists": SUMMARY_SCREEN,
    "Shots": SUMMARY_SCREEN,
    "ShotAccuracy": SUMMARY_SCREEN,
    "Passes": SUMMARY_SCREEN,
    "PassAccuracy": SUMMARY_SCREEN,
    "Dribbles": SUMMARY_SCREEN,
    "DribbleSuccessRate": SUMMARY_SCREEN,
    "Tackles": SUMMARY_SCREEN,
    "TackleSuccessRate": SUMMARY_SCREEN,
    "Offsides": SUMMARY_SCREEN,
    "FoulsCommitted": SUMMARY_SCREEN,
    "PossessionWon": SUMMARY_SCREEN,
    "PossessionLost": SUMMARY_SCREEN,
    "MinutesPlayed": SUMMARY_SCREEN,
    "DistanceCovered": SUMMARY_SCREEN,
    "DistanceSprinted": SUMMARY_SCREEN,
    "YellowCard": SUMMARY_SCREEN,
    "RedCard": SUMMARY_SCREEN,
    "Possession": POSSESSION_SCREEN,
    "DribblesCompleted": POSSESSION_SCREEN,
    "DistanceDribbled": POSSESSION_SCREEN,
    "CornersWon": POSSESSION_SCREEN,
    "FoulsWon": POSSESSION_SCREEN,
    "PenaltiesWon": POSSESSION_SCREEN,
    "AssitsFromDummy": POSSESSION_SCREEN,
    "RegularDribble": POSSESSION_SCREEN,
    "ShieldDribble": POSSESSION_SCREEN,
    "StrafeDribble": POSSESSION_SCREEN,
    "AgileDribble": POSSESSION_SCREEN,
    "Beat": POSSESSION_SCREEN,
    "SkillmoveBeat": POSSESSION_SCREEN,
    "Nutmeg": POSSESSION_SCREEN,
    "KnockOns": POSSESSION_SCREEN,
    "xGExcludingPenalties": SHOOTING_SCREEN,
    "ShotsOnTarget": SHOOTING_SCREEN,
    "ShotsOffTarget": SHOOTING_SCREEN,
    "ShotsBlocked": SHOOTING_SCREEN,
    "FreeKickGoals": SHOOTING_SCREEN,
    "AssistsFromShots": SHOOTING_SCREEN,
    "NormalShots": SHOOTING_SCREEN,
    "FinesseShots": SHOOTING_SCREEN,
    "HeaderShots": SHOOTING_SCREEN,
    "PowerShots": SHOOTING_SCREEN,
    "VolleyShots": SHOOTING_SCREEN,
    "ChipShots": SHOOTING_SCREEN,
    "SetPiecesShots": SHOOTING_SCREEN,
    "ExpectedAssists": PASSING_SCREEN,
    "SecondAssists": PASSING_SCREEN,
    "KeyPasses": PASSING_SCREEN,
    "PlayersBeatenByPasses": PASSING_SCREEN,
    "PassesCompleted": PASSING_SCREEN,
    "PassesIntercepted": PASSING_SCREEN, # passes that have been played by yourself but have been intercepted
    "OffsidePasses": PASSING_SCREEN,
    "CrossesAttemted": PASSING_SCREEN,
    "SuccessfulCrosses": PASSING_SCREEN,
    "CrossesBlocked": PASSING_SCREEN,
    "PassesAttemptedUnderPressure": PASSING_SCREEN,
    "PassesCompletedUnderPressure": PASSING_SCREEN,
    "GroundPasses": PASSING_SCREEN,
    "LobPasses": PASSING_SCREEN,
    "ThroughPasses": PASSING_SCREEN,
    "LoftedThroughPasses": PASSING_SCREEN,
    "Crosses": PASSING_SCREEN,
    "SetPiecesPasses": PASSING_SCREEN,
    "Interceptions": DEFENDING_SCREEN,
    "AerialDuels": DEFENDING_SCREEN,
    "AerialDuelsWon": DEFENDING_SCREEN,
    "BeatenByOpponent": DEFENDING_SCREEN
}

# dictionary that defines the expected range for game data
game_exp_range_dict = {
    "Possession": [20, 80],
    "Shots": [0, 30],
    "ExpectedGoals": [0, 20],
    "Passes": [0, 400],
    "Tackles": [0, 50],
    "TacklesWon": [0, 50],
    "Interceptions": [0, 50],
    "Saves": [0, 50],
    "FoulsCommitted": [0, 50],
    "Offsides": [0, 50],
    "Corners": [0, 30],
    "FreeKicks": [0, 20],
    "PenaltyKicks": [0, 10],
    "YellowCards": [0, 11],
    "RedCards": [0, 6],
    "DribbleSuccessRate": [0, 100],
    "ShotAccuracy": [0, 100],
    "PassAccuracy": [0, 100]
}

# dictionary that defines the expected range for player data
player_exp_range_dict = {
    "Rating": [2, 10],
    "Goals": [0, 10],
    "Assists": [0, 10],
    "Shots": [0, 20],
    "ShotAccuracy": [0, 100],
    "Passes": [0, 100],
    "PassAccuracy": [0, 100],
    "Dribbles": [0, 100],
    "DribbleSuccessRate": [0, 100],
    "Tackles": [0, 100],
    "TackleSuccessRate": [0, 100],
    "Offsides": [0, 100],
    "FoulsCommitted": [0, 100],
    "PossessionWon": [0, 100],
    "PossessionLost": [0, 100],
    "MinutesPlayed": [0, 100],
    "DistanceCovered": [0, 100],
    "DistanceSprinted": [0, 100],
    "Possession": [0, 50],
    "DribblesCompleted": [0, 20],
    "DistanceDribbled": [0, 10],
    "CornersWon": [0, 12],
    "FoulsWon": [0, 10],
    "PenaltiesWon": [0, 3],
    "AssitsFromDummy": [0, 10],
    "RegularDribble": [0, 100],
    "ShieldDribble": [0, 100],
    "StrafeDribble": [0, 100],
    "AgileDribble": [0, 100],
    "Beat": [0, 20],
    "SkillmoveBeat": [0, 10],
    "Nutmeg": [0, 4],
    "KnockOns": [0, 20],
    "xGExcludingPenalties": [0, 15],
    "ShotsOnTarget": [0, 15],
    "ShotsOffTarget": [0, 15],
    "ShotsBlocked": [0, 10],
    "FreeKickGoals": [0, 5],
    "AssistsFromShots": [0, 10],
    "NormalShots": [0, 20],
    "FinesseShots": [0, 20],
    "HeaderShots": [0, 10],
    "PowerShots": [0, 20],
    "VolleyShots": [0, 20],
    "ChipShots": [0, 10],
    "SetPiecesShots": [0, 10],
    "ExpectedAssists": [0, 10],
    "SecondAssists": [0, 10],
    "KeyPasses": [0, 30],
    "PlayersBeatenByPasses": [0, 50],
    "PassesCompleted": [0, 100],
    "PassesIntercepted": [0, 50], # passes that have been played by yourself but have been intercepted
    "OffsidePasses": [0, 20],
    "CrossesAttemted": [0, 20],
    "SuccessfulCrosses": [0, 20],
    "CrossesBlocked": [0, 20],
    "PassesAttemptedUnderPressure": [0, 30],
    "PassesCompletedUnderPressure": [0, 30],
    "GroundPasses": [0, 100],
    "LobPasses": [0, 100],
    "ThroughPasses": [0, 100],
    "LoftedThroughPasses": [0, 100],
    "Crosses": [0, 20],
    "SetPiecesPasses": [0, 20],
    "Interceptions": [0, 15],
    "AerialDuels": [0, 15],
    "AerialDuelsWon": [0, 15],
    "BeatenByOpponent": [0, 20],
    "YellowCard": [0, 1],
    "RedCard": [0, 1]
}

# dictionary that defines the valid range for game data
game_valid_range_dict = {
    "Possession": [0, 100],
    "Shots": [0, MAX_VALUE],
    "ExpectedGoals": [0, MAX_VALUE],
    "Passes": [0, MAX_VALUE],
    "Tackles": [0, MAX_VALUE],
    "TacklesWon": [0, MAX_VALUE],
    "Interceptions": [0, MAX_VALUE],
    "Saves": [0, MAX_VALUE],
    "FoulsCommitted": [0, MAX_VALUE],
    "Offsides": [0, MAX_VALUE],
    "Corners": [0, MAX_VALUE],
    "FreeKicks": [0, MAX_VALUE],
    "PenaltyKicks": [0, MAX_VALUE],
    "YellowCards": [0, 11],
    "RedCards": [0, 11],
    "DribbleSuccessRate": [0, 100],
    "ShotAccuracy": [0, 100],
    "PassAccuracy": [0, 100]
}

# dictionary that defines the valid range for player data
player_valid_range_dict = {
    "Rating": [0, 10],
    "Goals": [0, MAX_VALUE],
    "Assists": [0, MAX_VALUE],
    "Shots": [0, MAX_VALUE],
    "ShotAccuracy": [0, 100],
    "Passes": [0, MAX_VALUE],
    "PassAccuracy": [0, 100],
    "Dribbles": [0, MAX_VALUE],
    "DribbleSuccessRate": [0, 100],
    "Tackles": [0, MAX_VALUE],
    "TackleSuccessRate": [0, 100],
    "Offsides": [0, MAX_VALUE],
    "FoulsCommitted": [0, MAX_VALUE],
    "PossessionWon": [0, MAX_VALUE],
    "PossessionLost": [0, MAX_VALUE],
    "MinutesPlayed": [0, MAX_VALUE],
    "DistanceCovered": [0, MAX_VALUE],
    "DistanceSprinted": [0, MAX_VALUE],
    "Possession": [0, 100],
    "DribblesCompleted": [0, MAX_VALUE],
    "DistanceDribbled": [0, MAX_VALUE],
    "FoulsWon": [0, MAX_VALUE],
    "PenaltiesWon": [0, MAX_VALUE],
    "RegularDribble": [0, 100],
    "ShieldDribble": [0, 100],
    "StrafeDribble": [0, 100],
    "Beat": [0, MAX_VALUE],
    "SkillmoveBeat": [0, MAX_VALUE],
    "Nutmeg": [0, MAX_VALUE],
    "KnockOns": [0, MAX_VALUE],
    "ShotsOnTarget": [0, MAX_VALUE],
    "ShotsOffTarget": [0, MAX_VALUE],
    "ShotsBlocked": [0, MAX_VALUE],
    "NormalShots": [0, MAX_VALUE],
    "FinesseShots": [0, MAX_VALUE],
    "HeaderShots": [0, MAX_VALUE],
    "LowShots": [0, MAX_VALUE],
    "VolleyShots": [0, MAX_VALUE],
    "ChipShots": [0, MAX_VALUE],
    "SetPiecesShots": [0, MAX_VALUE],
    "ExpectedAssits": [0, MAX_VALUE],
    "PassesCompleted": [0, MAX_VALUE],
    "PassesIntercepted": [0, MAX_VALUE], # passes that have been played by yourself but have been intercepted
    "OffsidePasses": [0, MAX_VALUE],
    "GroundPasses": [0, MAX_VALUE],
    "LobPasses": [0, MAX_VALUE],
    "ThroughPasses": [0, MAX_VALUE],
    "LoftedThroughPass": [0, MAX_VALUE],
    "Crosses": [0, MAX_VALUE],
    "PassesSetPieces": [0, MAX_VALUE],
    "AirDuelsWon": [0, MAX_VALUE],
    "BeatenByOpponent": [0, MAX_VALUE],
    "YellowCard": [0, 1],
    "RedCard": [0, 1],
}