MAX_VALUE = 1000000

# list with all attributes from the match facts screen
game_data_attr = ["Possession", "Shots", "ExpectedGoals", "Passes",
    "Tackles", "TacklesWon", "Interceptions", "Saves", "Saves", "FoulsCommitted", "Offsides",
    "Corners", "FreeKicks", "PenaltyKicks", "YellowCards", "RedCards", "DribbleSuccessRate",
    "ShotAccuracy", "PassAccuracy"]

# list with all attributes from the player performance screen
player_data_attr = ["Rating", "Goals", "Assists", "Shots", "ShotAccuracy", "Passes", "PassAccuracy",
    "Dribbles", "DribbleSuccessRate", "Tackles", "TackleSuccessRate", "Offsides", "FoulsCommitted",
    "PossessionWon", "PossessionLost", "MinutesPlayed", "DistanceCovered", "DistanceSprinted", "YellowCard",
    "RedCard", "Possession", "DribblesCompleted", "DistanceDribbled", "FoulsWon", "PenaltiesWon", "RegularDribble",
    "ShieldDribble", "StrafeDribble", "Beat", "SkillmoveBeat", "Nutmeg", "KnockOns", "ShotsOnTarget",
    "ShotsOffTarget", "ShotsBlocked", "NormalShots", "FinesseShots", "HeaderShots", "LowShots", "VolleyShots", "ChipShots",
    "SetPiecesShots", "ExpectedAssits", "PassesCompleted", "PassesIntercepted", "OffsidePasses", "GroundPasses", "LobPasses",
    "ThroughPasses", "LoftedThroughPasses", "Crosses", "PassesSetPieces", "AirDuelsWon", "BeatenByOpponent"]


# dictionary that defines the expected range for game data
game_exp_range_dict = {
    "Possession": [20, 80],
    "Shots": [0, 30],
    "ExpectedGoals": [0, 20],
    "Passes": [0, 500],
    "Tackles": [0, 100],
    "TacklesWon": [0, 100],
    "Interceptions": [0, 100],
    "Saves": [0, 100],
    "FoulsCommitted": [0, 100],
    "Offsides": [0, 100],
    "Corners": [0, 50],
    "FreeKicks": [0, 50],
    "PenaltyKicks": [0, 10],
    "YellowCards": [0, 11],
    "RedCards": [0, 6],
    "DribbleSuccessRate": [0, 100],
    "ShotAccuracy": [0, 100],
    "PassAccuracy": [40, 90]
}

# dictionary that defines the expected range for player data
player_exp_range_dict = {
    "Rating": [0, 10],
    "Goals": [0, 10],
    "Assists": [0, 10],
    "Shots": [0, 20],
    "ShotAccuracy": [0, 100],
    "Passes": [0, 100],
    "PassAccuracy": [0, 100],
    "Dribbles": [0, 100],
    "DribbleSuccessRate": [0, 100],
    "Tackles": [0, 100],
    "TackleSuccessRate": [0, 100],
    "Offsides": [0, 100],
    "FoulsCommitted": [0, 100],
    "PossessionWon": [0, 100],
    "PossessionLost": [0, 100],
    "MinutesPlayed": [0, 100],
    "DistanceCovered": [0, 100],
    "DistanceSprinted": [0, 100],
    "YellowCard": [0, 1],
    "RedCard": [0, 1],
    "Possession": [0, 50],
    "DribblesCompleted": [0, 20],
    "DistanceDribbled": [0, 10],
    "FoulsWon": [0, 10],
    "PenaltiesWon": [0, 3],
    "RegularDribble": [0, 10],
    "ShieldDribble": [0, 10],
    "StrafeDribble": [0, 10],
    "Beat": [0, 20],
    "SkillmoveBeat": [0, 10],
    "Nutmeg": [0, 3],
    "KnockOns": [0, 20],
    "ShotsOnTarget": [0, 15],
    "ShotsOffTarget": [0, 15],
    "ShotsBlocked": [0, 10],
    "NormalShots": [0, 20],
    "FinesseShots": [0, 20],
    "HeaderShots": [0, 10],
    "LowShots": [0, 20],
    "VolleyShots": [0, 20],
    "ChipShots": [0, 10],
    "SetPiecesShots": [0, 10],
    "ExpectedAssits": [0, 10],
    "PassesCompleted": [0, 100],
    "PassesIntercepted": [0, 50], # passes that have been played by yourself but have been intercepted
    "OffsidePasses": [0, 20],
    "GroundPasses": [0, 100],
    "LobPasses": [0, 100],
    "ThroughPasses": [0, 100],
    "LoftedThroughPasses": [0, 100],
    "Crosses": [0, 20],
    "PassesSetPieces": [0, 30],
    "AirDuelsWon": [0, 20],
    "BeatenByOpponent": [0, 20]
}

# dictionary that defines the valid range for game data
game_valid_range_dict = {
    "Possession": [0, 100],
    "Shots": [0, MAX_VALUE],
    "ExpectedGoals": [0, MAX_VALUE],
    "Passes": [0, MAX_VALUE],
    "Tackles": [0, MAX_VALUE],
    "TacklesWon": [0, MAX_VALUE],
    "Interceptions": [0, MAX_VALUE],
    "Saves": [0, MAX_VALUE],
    "FoulsCommitted": [0, MAX_VALUE],
    "Offsides": [0, MAX_VALUE],
    "Corners": [0, MAX_VALUE],
    "FreeKicks": [0, MAX_VALUE],
    "PenaltyKicks": [0, MAX_VALUE],
    "YellowCards": [0, 11],
    "RedCards": [0, 11],
    "DribbleSuccessRate": [0, 100],
    "ShotAccuracy": [0, 100],
    "PassAccuracy": [0, 100]
}

# dictionary that defines the valid range for player data
player_valid_range_dict = {
    "Rating": [0, 10],
    "Goals": [0, MAX_VALUE],
    "Assists": [0, MAX_VALUE],
    "Shots": [0, MAX_VALUE],
    "ShotAccuracy": [0, 100],
    "Passes": [0, MAX_VALUE],
    "PassAccuracy": [0, 100],
    "Dribbles": [0, MAX_VALUE],
    "DribbleSuccessRate": [0, 100],
    "Tackles": [0, MAX_VALUE],
    "TackleSuccessRate": [0, 100],
    "Offsides": [0, MAX_VALUE],
    "FoulsCommitted": [0, MAX_VALUE],
    "PossessionWon": [0, MAX_VALUE],
    "PossessionLost": [0, MAX_VALUE],
    "MinutesPlayed": [0, MAX_VALUE],
    "DistanceCovered": [0, MAX_VALUE],
    "DistanceSprinted": [0, MAX_VALUE],
    "YellowCard": [0, 1],
    "RedCard": [0, 1],
    "Possession": [0, 100],
    "DribblesCompleted": [0, MAX_VALUE],
    "DistanceDribbled": [0, MAX_VALUE],
    "FoulsWon": [0, MAX_VALUE],
    "PenaltiesWon": [0, MAX_VALUE],
    "RegularDribble": [0, MAX_VALUE],
    "ShieldDribble": [0, MAX_VALUE],
    "StrafeDribble": [0, MAX_VALUE],
    "Beat": [0, MAX_VALUE],
    "SkillmoveBeat": [0, MAX_VALUE],
    "Nutmeg": [0, MAX_VALUE],
    "KnockOns": [0, MAX_VALUE],
    "ShotsOnTarget": [0, MAX_VALUE],
    "ShotsOffTarget": [0, MAX_VALUE],
    "ShotsBlocked": [0, MAX_VALUE],
    "NormalShots": [0, MAX_VALUE],
    "FinesseShots": [0, MAX_VALUE],
    "HeaderShots": [0, MAX_VALUE],
    "LowShots": [0, MAX_VALUE],
    "VolleyShots": [0, MAX_VALUE],
    "ChipShots": [0, MAX_VALUE],
    "SetPiecesShots": [0, MAX_VALUE],
    "ExpectedAssits": [0, MAX_VALUE],
    "PassesCompleted": [0, MAX_VALUE],
    "PassesIntercepted": [0, MAX_VALUE], # passes that have been played by yourself but have been intercepted
    "OffsidePasses": [0, MAX_VALUE],
    "GroundPasses": [0, MAX_VALUE],
    "LobPasses": [0, MAX_VALUE],
    "ThroughPasses": [0, MAX_VALUE],
    "LoftedThroughPass": [0, MAX_VALUE],
    "Crosses": [0, MAX_VALUE],
    "PassesSetPieces": [0, MAX_VALUE],
    "AirDuelsWon": [0, MAX_VALUE],
    "BeatenByOpponent": [0, MAX_VALUE]
}